# Generated by Django 5.2 on 2025-07-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('user_id', models.CharField(max_length=500, unique=True)),
                ('doc_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=50, unique=True)),
                ('collection_id', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
